name: Build Firmware
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install pipx & PlatformIO
        run: |
          python -m pip install --upgrade pip pipx
          python -m pipx ensurepath
          echo "export PATH=~/.local/bin:$PATH" >> $GITHUB_ENV
          ~/.local/bin/pipx install platformio
      - name: Cache PIO
        uses: actions/cache@v4
        with:
          path: |
            ~/.platformio
          key: pio-${{ runner.os }}-${{ hashFiles('platformio.ini') }}
      - name: PlatformIO Build
        run: |
          ~/.local/bin/pio pkg update
          ~/.local/bin/pio run -e esp32dev
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: .pio/build/esp32dev/firmware.bin